### ISSUE TITLE
Write images to configurable directory instead the same as original image

### ISSUE THREAD

**Issue by cve** [Folkloreatelier/laravel-image#7]
Hi,

suppose I have custom filter called 'product_view' with size 120x120 and my original images was uploaded to public/uploads/photos.

When I set write option to true, then the package writes generated thumbnail into the same directory as original, so when my filter settings has been changed for example to size 110x110 then generated thumbnail is no longer valid, cause it exists but with 120x120 size, so I have to remove it for regenerate with the next request.

When the write image path will be configurable then I can set it to i.e. public/uploads/thumbs and then clean this directory for the regeneration.

Or it may be other possible solution for this problem?

**Comment by dmongeau** [comment]
The problem with that, is that the generated thumbnails won't be at the same place than the original images so the .htaccess won't bypass PHP. I was thinking about adding an artisan command to easily clear the generated images because this method is already available on the Image Facade `Image:: deleteManipulated($path);` it just a matter of wrapping it in an Artisan command.

Also another possible solution could be to add another folder in the `src_dirs` config. This way, you are able to use a different path in the `Image::url()` method that is not necessarily relative to `public_path`
